package com.his.reports.service;

import com.his.reports.entity.ReportLogEntity;
import com.his.reports.repository.ReportLogRepository;
import com.his.reports.service.ReportService;
import com.his.reports.entity.EdEligEntity;
import com.his.reports.repository.EdEligRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

@Service
public class ReportServiceImpl implements ReportService {

    @Autowired
    private EdEligRepository edRepo;

    @Autowired
    private ReportLogRepository logRepo;

    @Value("${reports.output.dir}")
    private String reportsDir;   //  configurable path


    public File generateDailyReport(LocalDate date) {
        LocalDateTime startOfDay = date.atStartOfDay();
        LocalDateTime endOfDay = date.atTime(LocalTime.MAX);

        List<EdEligEntity> records = edRepo.findByPlanStartDateBetween(startOfDay, endOfDay);
        File file =generateReport(records, "Daily Report", "Daily_Report_" + date + ".xlsx");
       return file;
    }

    // Runs every day at 6 PM IST
    @Scheduled(cron = "0 0 18 * * ?")
    public void autoGenerateDailyReport() {
        LocalDate date = LocalDate.now();   // current date
        LocalDateTime startOfDay = date.atStartOfDay();
        LocalDateTime endOfDay = date.atTime(LocalTime.MAX);

        List<EdEligEntity> records = edRepo.findByPlanStartDateBetween(startOfDay, endOfDay);
        generateReport(records, "Auto Daily Report", "Auto_Daily_Report_" + date + ".xlsx");
    }


    @Override
    public File generatePlanWiseReport(String planName) {
        List<EdEligEntity> records = edRepo.findByPlanName(planName);
        return generateReport(records, "Plan Wise Report", "PlanWise_" + planName + ".xlsx");
    }

    @Override
    public File generateStatusWiseReport(String status) {
        List<EdEligEntity> records = edRepo.findByPlanStatus(status);
        return generateReport(records, "Status Wise Report", "StatusWise_" + status + ".xlsx");
    }


    @Override
    public File generateDateRangeReport(LocalDate startDate, LocalDate endDate) {
        LocalDateTime startDateTime = startDate.atStartOfDay();
        LocalDateTime endDateTime = endDate.atTime(LocalTime.MAX);

        List<EdEligEntity> records = edRepo.findByPlanStartDateBetween(startDateTime, endDateTime);

        return generateReport(records, "Date Range Report",
                "DateRange_" + startDate + "_to_" + endDate + ".xlsx");
    }


    private File generateReport(List<EdEligEntity> records, String type, String fileName) {
        File dir = new File(reportsDir);
        if (!dir.exists()) {
            dir.mkdirs();  // auto create folder if missing
        }

        File file = new File(dir, fileName);
        exportToExcel(records, file);
        saveLog(type, file.getName());
        return file;
    }

    private void exportToExcel(List<EdEligEntity> records, File file) {
        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Report");
            Row header = sheet.createRow(0);
            header.createCell(0).setCellValue("CASE_NUM");
            header.createCell(1).setCellValue("PLAN_NAME");
            header.createCell(2).setCellValue("PLAN_STATUS");
            header.createCell(3).setCellValue("BENEFIT_AMT");
            header.createCell(4).setCellValue("PLAN_START_DATE");

            int rowNum = 1;
            for (EdEligEntity e : records) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(e.getCaseNum());
                row.createCell(1).setCellValue(e.getPlanName());
                row.createCell(2).setCellValue(e.getPlanStatus());
                row.createCell(3).setCellValue(e.getBenefitAmt());
                row.createCell(4).setCellValue(e.getPlanStartDate().toString());
            }

            try (FileOutputStream fos = new FileOutputStream(file)) {
                workbook.write(fos);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void saveLog(String type, String fileName) {
        ReportLogEntity log = new ReportLogEntity();
        log.setReportType(type);
        log.setGeneratedDate(LocalDateTime.now());
        log.setFileName(fileName);
        log.setStatus("SUCCESS");
        logRepo.save(log);
    }
}
