pipeline {
    agent any
    // --- Add parameters block to accept IMAGE_TAG from parent ---
        parameters {
            string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag passed from parent pipeline')
        }
    environment {
        AWS_ACCOUNT_ID = "802749364888"
        AWS_REGION = "ap-south-1"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        //IMAGE_TAG = "${params.IMAGE_TAG}"
        EC2_HOST = "ubuntu@52.66.168.244"
        EC2_KEY = "/var/lib/jenkins/.ssh/his-key-ap-south-1-openssh.pem"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/deepamunesh/his-project.git'
            }
        }
        stage('Build JAR') {
            steps {
                // --- CHANGE: Added Maven local repo caching to reuse dependencies ---
                // Earlier: sh 'mvn clean package -DskipTests'
                // Now: using -Dmaven.repo.local to avoid downloading dependencies every time
                sh 'mvn clean package -Dmaven.repo.local=/var/jenkins_home/.m2/repository -DskipTests'
            }
        }
stage('Docker Build & Push') {
            steps {
                sh """
                    # --- AWS ECR Login (mandatory for push) ---
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}

                    # --- Build Docker image ---
                    # Folder name must match repo folder exactly
                    # For ed-rules-service → ED-RULES-API/
                    docker build -t ed-rules-service:${params.IMAGE_TAG} ED-RULES-API/

                    # --- Tag image for ECR ---
                    docker tag ed-rules-service:${params.IMAGE_TAG} ${ECR_REGISTRY}/ed-rules-service:${params.IMAGE_TAG}

                    # --- Push image to ECR ---
                    docker push ${ECR_REGISTRY}/ed-rules-service:${params.IMAGE_TAG}
                """
            }
        }
    }
}
