pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID = "802749364888"
        AWS_REGION = "ap-south-1"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        IMAGE_TAG = "${BUILD_NUMBER}"
        EC2_HOST = "ubuntu@52.66.168.244"
        EC2_KEY = "/var/lib/jenkins/.ssh/his-key-ap-south-1-openssh.pem"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/deepamunesh/his-project.git'
            }
        }
        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh """
                    # --- AWS ECR Login Step Added ---
                    # Without this, docker push fails with 403 Forbidden
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}

                    # Build Docker image
                    docker build -t config-server:${IMAGE_TAG} CONFIG-SERVER/

                    # Tag image for ECR
                    docker tag config-server:${IMAGE_TAG} ${ECR_REGISTRY}/config-server:${IMAGE_TAG}

                    # Push image to ECR
                    docker push ${ECR_REGISTRY}/config-server:${IMAGE_TAG}
                """
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    # Copy updated compose file to EC2
                    scp -i ${EC2_KEY} docker-compose.yml ${EC2_HOST}:/home/ubuntu/his-deployment/

                    # Login to ECR and deploy with IMAGE_TAG
                    ssh -i ${EC2_KEY} ${EC2_HOST} "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY} && cd /home/ubuntu/his-deployment && IMAGE_TAG=${BUILD_NUMBER} docker-compose pull && IMAGE_TAG=${BUILD_NUMBER} docker-compose up -d"
                '''
            }
        }
    }
}
