pipeline {
    agent any
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag passed from parent pipeline')
    }
    environment {
        AWS_ACCOUNT_ID = "802749364888"
        AWS_REGION = "ap-south-1"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        EC2_HOST = "ubuntu@52.66.168.244"
        EC2_KEY = "/var/lib/jenkins/.ssh/his-key-ap-south-1-openssh.pem"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/deepamunesh/his-project.git'
            }
        }
        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh """
                    # --- AWS ECR Login (mandatory for push) ---
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}

                    # --- Build Docker image ---
                    # Folder name must match repo folder exactly
                    # For Config-Server → CONFIG-SERVER/
                    docker build -t config-server:${params.IMAGE_TAG} CONFIG-SERVER/

                    # --- Tag image for ECR ---
                    docker tag config-server:${params.IMAGE_TAG} ${ECR_REGISTRY}/config-server:${params.IMAGE_TAG}

                    # --- Push image to ECR ---
                    docker push ${ECR_REGISTRY}/config-server:${params.IMAGE_TAG}
                """
            }
        }
    }
}
