package com.his.reports.controller;

import com.his.reports.service.ReportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;

@RestController
@RequestMapping("/reports")
public class ReportController {

    @Autowired
    private ReportService reportService;

    @GetMapping("/daily/{date}")
    public ResponseEntity<String> generateDaily(@PathVariable String date) {
        LocalDate localDate = LocalDate.parse(date); // parse simple date
        File file = reportService.generateDailyReport(localDate);
        return ResponseEntity.ok("Report generated: " + file.getAbsolutePath());
    }
    @GetMapping("/automatciDailyReports/{date}")
    public ResponseEntity<String>  autoGenerateDailyReport(@PathVariable String date) {
        LocalDate localDate = LocalDate.parse(date);
        File file = reportService.generateDailyReport(localDate);
        return ResponseEntity.ok("Daily report generated automatically for date:"  + file.getAbsolutePath());

    }

    @GetMapping("/plan/{planName}")
    public ResponseEntity<String> generatePlanWise(@PathVariable String planName) {
        File file = reportService.generatePlanWiseReport(planName);
        return ResponseEntity.ok("Report generated: " + file.getAbsolutePath());
    }

    @GetMapping("/status/{status}")
    public ResponseEntity<String> generateStatusWise(@PathVariable String status) {
        File file = reportService.generateStatusWiseReport(status);
        return ResponseEntity.ok("Report generated: " + file.getAbsolutePath());
    }

    @GetMapping("/daterange")
    public ResponseEntity<String> generateDateRange(@RequestParam String start, @RequestParam String end) {
        LocalDate startDate = LocalDate.parse(start);   // parse simple date
        LocalDate endDate = LocalDate.parse(end);

        File file = reportService.generateDateRangeReport(startDate, endDate);
        return ResponseEntity.ok("Report generated: " + file.getAbsolutePath());
    }

}
