pipeline {
    agent any
    // --- Add parameters block to accept IMAGE_TAG from parent ---
        parameters {
            string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag passed from parent pipeline')
        }
    environment {
        AWS_ACCOUNT_ID = "802749364888"
        AWS_REGION = "ap-south-1"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        //IMAGE_TAG = "${params.IMAGE_TAG}"
        EC2_HOST = "ubuntu@52.66.168.244"
        EC2_KEY = "/var/lib/jenkins/.ssh/his-key-ap-south-1-openssh.pem"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/deepamunesh/his-project.git'
            }
        }
        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
       stage('Docker Build & Push') {
            steps {
                sh """
                    # --- AWS ECR Login (mandatory for push) ---
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}

                    # --- Build Docker image ---
                    #  Folder name must match repo folder exactly
                    # For auth-service → AUTH-SERVICE/
                    docker build -t auth-service:${params.IMAGE_TAG} AUTH-SERVICE/

                    # --- Tag image for ECR ---
                    docker tag auth-service:${params.IMAGE_TAG} ${ECR_REGISTRY}/auth-service:${params.IMAGE_TAG}

                    # --- Push image to ECR ---
                    docker push ${ECR_REGISTRY}/auth-service:${params.IMAGE_TAG}
                """
            }
        }
          stage('Deploy') {
                     steps {
                         sh """
                             # --- Copy docker-compose.yml from repo root to EC2 ---
                             # Path is root level now, same for all services
                             scp -i ${EC2_KEY} docker-compose.yml ${EC2_HOST}:/home/ubuntu/his-deployment/

                             # --- Run deploy commands on EC2 ---
                             ssh -i ${EC2_KEY} ${EC2_HOST} '
                                 cd /home/ubuntu/his-deployment &&
                                 aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY} &&
                                 echo IMAGE_TAG=${params.IMAGE_TAG} > .env &&
                                 export IMAGE_TAG=${params.IMAGE_TAG} &&
                                 docker-compose pull &&
                                 docker-compose up -d
                             '
                         """
                     }
                 }
    }
}
