pipeline {
    agent any
    // --- Add parameters block to accept IMAGE_TAG from parent ---
        parameters {
            string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag passed from parent pipeline')
        }
    environment {
        AWS_ACCOUNT_ID = "802749364888"
        AWS_REGION = "ap-south-1"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        //IMAGE_TAG = "${params.IMAGE_TAG}"
        EC2_HOST = "ubuntu@52.66.168.244"
        EC2_KEY = "/var/lib/jenkins/.ssh/his-key-ap-south-1-openssh.pem"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/deepamunesh/his-project.git'
            }
        }
        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh """
                    # --- AWS ECR Login Step Added ---
                    # Without this, docker push fails with 403 Forbidden
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                    docker build -t balance-issuance-service:${params.IMAGE_TAG} BALLANCE-ISSUANCE/
                    docker tag balance-issuance-service:${params.IMAGE_TAG} ${ECR_REGISTRY}/balance-issuance-service:${params.IMAGE_TAG}
                    docker push ${ECR_REGISTRY}/balance-issuance-service:${params.IMAGE_TAG}
                """
            }
        }
         stage('Deploy') {
                     steps {
                         sh '''
                             # Copy updated compose file to EC2
                             scp -i ${EC2_KEY} docker-compose.yml ${EC2_HOST}:/home/ubuntu/his-deployment/
                             ssh -i ${EC2_KEY} ${EC2_HOST} "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY} && cd /home/ubuntu/his-deployment && echo IMAGE_TAG=${params.IMAGE_TAG} > .env && docker-compose --env-file .env pull && docker-compose --env-file .env up -d"
                         '''
                     }
                 }
    }
}
